name: fg2
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - torchaudio
  - torchmetrics
  - torchtriton
  - cudatoolkit=11.8
  - opencv
  - matplotlib
  - scipy
  - scikit-learn
  - numpy<2
  - pillow
  - pyyaml
  - einops
  - tqdm
  - typing-extensions
  - yacs
  - ffmpeg
  - hdf5
  - ipython
  - jupyter
  - notebook
  - ninja
  - cmake
  - pip:
      - timm==0.9.16
      - xformers==0.0.25.post1
      - huggingface-hub==0.22.2
      - mmengine==0.10.4
      - openmim==0.3.9
      - pandas
      - tabulate
      - joblib

